package model.enums;

public enum TrapNames {
    MAGIC_CYLINDER,
    MIRROR_FORCE,
    MIND_CRUSH,
    TRAP_HOLE,
    TORRENTIAL_TRIBUTE,
    TIME_SEAL,
    NEGATE_ATTACK,
    SOLEMN_WARNING,
    MAGIC_JAMMER,
    CALL_OF_THE_HAUNTED;
}
