package view.viewcontroller;

public enum CardNames {
    BATTLE_OX("BattleOx"),
    AXE_RAIDER("AxeRaider"),
    YOMI_SHIP("YomiShip"),
    HORN_IMP("HornImp"),
    SILVER_FANG("SilverFang"),
    SUIJIN("Suijin"),
    FIREYAROU("Fireyarou"),
    CURTAIN_OF_THE_DARK_ONES("CurtainOfTheDarkOnes"),
    FERAL_IMP("FeralImp"),
    DARK_MAGICIAN("DarkMagician"),
    WATTKID("Wattkid"),
    BABY_DRAGON("BabyDragon"),
    HERO_OF_THE_EAST("HeroOfTheEast"),
    BATTLE_WARRIOR("BattleWarrior"),
    CRAWLING_DRAGON("CrawlingDragon"),
    FLAME_MANIPULATOR("FlameManipulator"),
    BLUE_EYES_WHITE_DRAGON("BlueEyesWhiteDragon"),
    CRAB_TURTLE("CrabTurtle"),
    SKULL_GUARDIAN("SkullGuardian"),
    SLOT_MACHINE("SlotMachine"),
    HANIWA("Haniwa"),
    MAN_EATER_BUG("ManEaterBug"),
    GATE_GUARDIAN("GateGuardian"),
    BITRON("Bitron"),
    MARSHMALLON("Marshmallon"),
    BEAST_KING_BARBAROS("BeastKingBarbaros"),
    TEXCHANGER("Texchanger"),
    LEOTRON("Leotron"),
    THE_CALCULATOR("TheCalculator"),
    ALEXANDRITE_DRAGON("AlexandriteDragon"),
    MIRAGE_DRAGON("MirageDragon"),
    HERALD_OF_CREATION("HeraldOfCreation"),
    EXPLODER_DRAGON("ExploderDragon"),
    WARRIOR_DAI_GREPHER("WarriorDaiGrepher"),
    DARK_BLADE("DarkBlade"),
    WATTAILDRAGON("Wattaildragon"),
    TERRATIGER_THE_EMPOWERED_WARRIOR("Terratiger"),
    THE_TRICKY("TheTricky"),
    SPIRAL_SERPENT("SpiralSerpent"),
    COMMAND_KNIGHT("CommandKnight"),

    TERRAFORMING("Terraforming"),
    POT_OF_GREED("PotOfGreed"),
    RAIGEKI("Raigeki"),
    HARPIES_FEATHER_DUSTER("HarpiesFeatherDuster"),
    SWORD_OF_REVEALING_LIGHT("SwordOfRevealingLight"),
    DARK_HOLE("DarkHole"),
    SUPPLY_SQUAD("SupplySquad"),
    SPELL_ABSORPTION("SpellAbsorption"),
    TWIN_TWISTERS("TwinTwisters"),
    MYSTICAL_SPACE_TYPHOON("MysticalSpaceTyphoon"),
    RING_OF_DEFENSE("RingOfDefense"),
    YAMI("Yami"),
    FOREST("Forest"),
    CLOSED_FOREST("ClosedForest"),
    UMIIRUKA("Umiiruka"),
    SWORD_OF_DARK_DESTRUCTION("SwordOfDarkDestruction"),
    BLACK_PENDANT("BlackPendant"),
    UNITED_WE_STAND("UnitedWeStand"),
    MAGNUM_SHIELD("MagnumShield"),
    ADVANCED_RITUAL_ART("AdvancedRitualArt"),
    TRAP_HOLE("TrapHole"),
    MIRROR_FORCE("MirrorForce"),
    MAGIC_CYLINDER("MagicCylinder"),
    MIND_CRASH("MindCrush"),
    TORRENTIAL_TRIBUTE("TorrentialTribute"),
    TIME_SEAL("TimeSeal"),
    NEGATE_ATTACK("NegateAttack"),
    SOLEMN_WARNING("SolemnWarning"),
    MAGIC_JAMMER("MagicJammer"),
    CALL_OF_THE_HAUNTED("CalloftheHunted"),
    UNKNOWN("Unknown");

    public final String imageName;

    CardNames(String imageName) {
        this.imageName = imageName;
    }
}
