module Yu.Gi.Oh {
    requires com.google.gson;
    requires jbcrypt;
    requires org.json;
    requires jetty.util;
    requires opencsv;
    requires commons.collections4;
    requires javafx.controls;
    requires javafx.base;
    requires javafx.fxml;
    requires javafx.media;
    requires javafx.graphics;
    requires lombok;
    exports server.control;
    opens server.control to com.google.gson, jbcrypt, org.json, jetty.util, opencsv, commons.collections4;
    exports server.control.game;
    opens server.control.game to com.google.gson, jbcrypt, org.json, jetty.util, opencsv, commons.collections4;
    exports server.control.databaseController;
    opens server.control.databaseController to lombok, com.google.gson, jbcrypt, org.json, jetty.util, opencsv, commons.collections4;
    exports server.model.card;
    opens server.model.card to com.google.gson, jbcrypt, org.json, jetty.util, opencsv, commons.collections4;
    exports server.model.game;
    opens server.model.game to com.google.gson, jbcrypt, org.json, jetty.util, opencsv, commons.collections4;
    exports server.model.user;
    opens server.model.user to com.google.gson, jbcrypt, org.json, jetty.util, opencsv, commons.collections4;
    exports client.view;
    opens client.view to javafx.controls, javafx.base, javafx.fxml, javafx.media, javafx.graphics;
    exports client.view.pages;
    opens client.view.pages to javafx.controls, javafx.base, javafx.fxml, javafx.media, javafx.graphics;
    exports client.view.controller;
    opens client.view.controller to org.json;
    exports client.view.model;
    opens client.view.model to javafx.base;
}